# Generated by Django 5.2.1 on 2025-05-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('chain', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('transfer', 'Transfer')], max_length=20)),
                ('asset_symbol', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cost_basis_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('realized_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crypto_tax_api.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'timestamp'], name='crypto_tax__wallet__c1d546_idx'), models.Index(fields=['wallet', 'asset_symbol'], name='crypto_tax__wallet__ed91d7_idx')],
                'unique_together': {('wallet', 'transaction_hash')},
            },
        ),
        migrations.CreateModel(
            name='TaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_realized_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('short_term_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('long_term_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_summaries', to='crypto_tax_api.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('current_price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='crypto_tax_api.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'asset_symbol')},
            },
        ),
    ]
