# Generated by Django 5.2.1 on 2025-05-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetholding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
