# Generated by Django 5.2.1 on 2025-05-17 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transactions_imported', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CexTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('asset_symbol', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('fee_asset', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cost_basis_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('realized_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cex_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'exchange', 'asset_symbol'], name='crypto_tax__user_id_1f04b1_idx'), models.Index(fields=['user', 'timestamp'], name='crypto_tax__user_id_024976_idx')],
                'unique_together': {('user', 'exchange', 'transaction_id')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('bybit', 'Bybit'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('ftx', 'FTX'), ('gemini', 'Gemini'), ('huobi', 'Huobi')], max_length=50)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
                ('api_passphrase', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exchange')},
            },
        ),
    ]
