# Generated by Django 5.2.1 on 2025-05-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0002_csvimport_cextransaction_exchangecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='cextransaction',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True),
        ),
    ]
