# Generated by Django 5.2.1 on 2025-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0003_cextransaction_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredential',
            name='last_sync_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
