# Generated by Django 5.2.1 on 2025-05-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0004_exchangecredential_last_sync_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredential',
            name='synced_until_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
