# Generated by Django 5.2.1 on 2025-05-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0005_exchangecredential_synced_until_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecredential',
            name='synced_until_timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('wallet', 'transaction_hash')},
        ),
    ]
