# Generated by Django 5.2.1 on 2025-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0006_remove_exchangecredential_synced_until_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredential',
            name='api_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='platform_type',
            field=models.CharField(choices=[('cex', 'Centralized Exchange'), ('dex_hybrid', 'DEX/Hybrid Platform')], default='cex', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='rate_limit_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('bybit', 'Bybit'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('ftx', 'FTX'), ('gemini', 'Gemini'), ('hyperliquid', 'Hyperliquid')], max_length=50),
        ),
    ]
