# Generated by Django 5.2.1 on 2025-06-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0007_exchangecredential_api_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('trading_fee', 'Trading Fee'), ('gas_fee', 'Gas Fee'), ('network_fee', 'Network Fee'), ('withdrawal_fee', 'Withdrawal Fee'), ('deposit_fee', 'Deposit Fee'), ('conversion_fee', 'Conversion Fee'), ('slippage_loss', 'Slippage Loss'), ('bridge_fee', 'Bridge Fee'), ('maker_fee', 'Maker Fee'), ('taker_fee', 'Taker Fee'), ('funding_fee', 'Funding Fee'), ('liquidation_fee', 'Liquidation Fee'), ('borrowing_fee', 'Interest/Borrowing Fee'), ('staking_fee', 'Staking Fee'), ('unstaking_fee', 'Unstaking Fee'), ('other_fee', 'Other Fee')], max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('fee_asset', models.CharField(max_length=50)),
                ('fee_usd_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_tax_deductible', models.BooleanField(default=True)),
                ('fee_description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('cex_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='crypto_tax_api.cextransaction')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='crypto_tax_api.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['fee_type', 'timestamp'], name='crypto_tax__fee_typ_5a883a_idx'), models.Index(fields=['is_tax_deductible'], name='crypto_tax__is_tax__ab971b_idx')],
            },
        ),
    ]
