# Generated by Django 5.2.1 on 2025-09-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0008_transactionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredential',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('api_key', 'API Key'), ('oauth', 'OAuth'), ('cdp', 'CDP Key')], default='api_key', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('coinbase_advanced', 'Coinbase Advanced Trade'), ('bybit', 'Bybit'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('ftx', 'FTX'), ('gemini', 'Gemini'), ('hyperliquid', 'Hyperliquid')], max_length=50),
        ),
    ]
