# Generated by Django 5.2.1 on 2025-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tax_api', '0009_add_cdp_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_confidence',
            field=models.CharField(choices=[('high', 'High - CEX/CoinGecko'), ('medium', 'Medium - DEX/GeckoTerminal'), ('low', 'Low - DexScreener/Recent'), ('none', 'None - Fallback')], default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_source',
            field=models.CharField(default='coingecko', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.CreateModel(
            name='TokenMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('decimals', models.IntegerField(default=18)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['contract_address'], name='crypto_tax__contrac_487c3b_idx'), models.Index(fields=['symbol'], name='crypto_tax__symbol_27b4c2_idx')],
            },
        ),
    ]
